apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: h8p6zbnvp-nodejs
  janus-idp.io/tekton: h8p6zbnvp-nodejs
  backstage.io/kubernetes-id: h8p6zbnvp-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: h8p6zbnvp-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
